name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_PATH }}
            git pull origin ${{ secrets.GIT_BRANCH }}
            npm install
            pm2 restart ${{ secrets.PM2_APP_NAME }}
            exit
          EOF

      - name: Cleanup
        run: rm -f private_key.pem
